services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - appnet
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/bookcase-realm.json:/opt/keycloak/data/import/bookcase-realm.json:ro

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - appnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d library" ]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db_password
      - db_user

  backend:
    build:
      context: ../LibraryApp
    image: ghcr.io/nataliacharz/library-backend:latest
    networks:
      - appnet
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10

  frontend:
    image: ghcr.io/nataliacharz/library-frontend:latest
    depends_on:
      - backend
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - appnet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  appnet:

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt

volumes:
  postgres_data:
  keycloak_data:
